### ISSUE TITLE
Rumble and gyro support

### ISSUE THREAD

**Issue by ekulabuhov** [wchill/SwitchInputEmulator#19]
Hey @wchill! Nice work! Do you know if there's a way to send gyroscope data to Switch? 
And a way to read rumble output?

Working on connecting PS4 to Switch using ESP32 and Arduino combo.

**Comment by wchill** [comment]
This isn't trivially possible with this project. As far as I know, in order for IMUs and rumble to work, you can't use the standard USB HID protocol (it *might* be doable by hacking the USB device headers, but most likely not).

As such, you need a full emulation of a Pro Controller or set of Joycons for that to work. I was working on this for some time and managed to get my Switch to recognize my fake Pro Controller, but it is considerably more complex to implement, as the Pro Controller uses its own protocol and communicates at a much higher rate. You will probably want a higher bandwidth, lower latency connection to your PC than what an Arduino or regular serial connection can provide as the Pro Controller's Broadcom chip communicates using a 3Mbps UART.

You can refer to [this repo](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering) for some more details on that, I used this information to write [this Python code](https://github.com/usb-tools/Facedancer/blob/master/USBProController.py) which only does enumeration; IMU and rumble aren't supported since I didn't have any way to test those two functions.

Note that if you also want to add NFC or IR camera support, you must implement Bluetooth support or get some Joycon rails so you can talk to the Switch directly over UART.
